version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
    environment:
      - PORT=8080
      - NODE_ENV=development
  nestjs:
    build: ./backend
    container_name: nestjs
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - THROTTLE_TTL=${THROTTLE_TTL}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - QDRANTURL=${QDRANTURL}
      - QDRANTAPIKEYS=${QDRANTAPIKEYS}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - NODE_ENV=${NODE_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - embed_service
  #    - qdrant
  #    - ollama
    restart: always

  # qdrant:
  #   image: qdrant/qdrant
  #   container_name: qdrant
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_data:/qdrant/storage
  #   restart: always

  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_models:/root/.ollama
  #   restart: always

  # embed_service:
  #   build: ./embed_service
  #   container_name: embed_service
  #   ports:
  #     - '5050:5050'
volumes:
  qdrant_data:
  ollama_models:
